"""Regenerate web/src/fixtures.ts from a live brain.

Runs the demo's opening beats against a fresh DB (skip the boots, skip the
crewneck, score the suit) so the offline dashboard shows a lived-in pond and
ledger, then snapshots GET /portfolio.

Usage: uvicorn brain.app:app --port 8000   # with a fresh PUDDLE_DB_PATH
       python scripts/gen_fixtures.py
"""

import json
import urllib.request
from pathlib import Path

BRAIN = "http://localhost:8000"
OUT = Path(__file__).parent.parent / "web" / "src" / "fixtures.ts"


def req(path, body=None, method=None):
    r = urllib.request.Request(
        BRAIN + path,
        data=json.dumps(body).encode() if body is not None else None,
        headers={"content-type": "application/json"},
        method=method or ("POST" if body is not None else "GET"),
    )
    return json.loads(urllib.request.urlopen(r).read())


def score(item_id):
    return req("/score_item", {"item_id": item_id, "now_hour": 23})


def skip(item_id, prediction_id, event):
    return req("/actions", {
        "event_id": event, "item_id": item_id, "prediction_id": prediction_id, "action": "skip",
    })


def main():
    boots = score("cand_boots")
    skip("cand_boots", boots["prediction_id"], "fixture-skip-boots")
    req(f"/predict/{boots['prediction_id']}/grade?correct=true", method="POST")

    crew = score("cand_crew4")
    skip("cand_crew4", crew["prediction_id"], "fixture-skip-crew")
    req(f"/predict/{crew['prediction_id']}/grade?correct=true", method="POST")

    score("cand_suit")  # left pending: the buy the demo is about to make

    view = req("/portfolio")
    header = (
        "// Offline fallback so the dashboard renders even if the brain isn't running.\n"
        "// Generated by scripts/gen_fixtures.py from a live brain; do not hand-edit.\n"
    )
    OUT.write_text(
        header
        + "export const FIXTURE = "
        + json.dumps(view, indent=2)
        + ";\nexport type Portfolio = typeof FIXTURE;\n"
    )
    print(f"wrote {OUT} (pond={view['pond']}, accuracy={view['ledger']['accuracy']})")


if __name__ == "__main__":
    main()
